name: qsymm-minimal
channels:
    - conda-forge
dependencies:
    - python=3.7
    - numpy=1.16.2
    - scipy=1.1.0
    - sympy=1.4
    - tinyarray=1.2.3
    ## Dev Dependencies
    # Testing
    - pytest
    - pytest-cov
    - pytest-flakes
    - pytest-pep8
